import type { FinancialConnectionProvider, FinancialConnectionRail } from '../types/core';

export interface FinancialConnectionProviderDefinition {
  providerKey: FinancialConnectionProvider;
  label: string;
  category: 'bank' | 'credit' | 'processor' | 'wallet' | 'card_program' | 'treasury' | 'postal' | 'government';
  connectionRail: FinancialConnectionRail;
  availabilityStatus: 'live' | 'profile_only' | 'bank_dependent';
  supportsLiveSync: boolean;
  supportsTransactionImport: boolean;
  supportsSettlementInitiation: boolean;
  supportsAchOrigination: boolean;
  supportsWireOrigination: boolean;
  supportsInstantRails: boolean;
  accountTypeHint: 'checking' | 'savings' | 'credit_card' | 'custodial' | 'other';
  executionReadiness: 'ready_now' | 'staged' | 'institution_dependent';
  supportedRails: string[];
  description: string;
  referralSignupUrl?: string;
}

const providerCatalog: FinancialConnectionProviderDefinition[] = [
  {
    providerKey: 'plaid',
    label: 'Plaid Institution Login',
    category: 'bank',
    connectionRail: 'plaid_link',
    availabilityStatus: 'live',
    supportsLiveSync: true,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: true,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'checking',
    executionReadiness: 'institution_dependent',
    supportedRails: ['ACH verification', 'bank feed sync', 'Transfer / ACH (provider-scoped)'],
    description:
      'Use a live institution login for bank and card issuers, keep linked accounts as permanent ERP and COA records, and treat ACH origination as provider-scoped rather than universally enabled.',
  },
  {
    providerKey: 'dwolla',
    label: 'Dwolla Treasury Rail',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: false,
    supportsSettlementInitiation: true,
    supportsAchOrigination: true,
    supportsWireOrigination: true,
    supportsInstantRails: false,
    accountTypeHint: 'checking',
    executionReadiness: 'staged',
    supportedRails: ['ACH credit', 'ACH debit', 'wire'],
    description:
      'Execution-focused ACH and wire provider profile for moving from retained ERP intent into real bank-originated transfers with provider status tracking.',
  },
  {
    providerKey: 'treasury_prime',
    label: 'Treasury Prime',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: false,
    supportsSettlementInitiation: true,
    supportsAchOrigination: true,
    supportsWireOrigination: true,
    supportsInstantRails: false,
    accountTypeHint: 'checking',
    executionReadiness: 'staged',
    supportedRails: ['ACH', 'same-day ACH', 'wire', 'bank ledger'],
    description:
      'Banking-as-a-service posture for ACH and wire origination when ClearFlow graduates from control to true bank-connected treasury execution.',
  },
  {
    providerKey: 'modern_treasury',
    label: 'Modern Treasury',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: false,
    supportsSettlementInitiation: true,
    supportsAchOrigination: true,
    supportsWireOrigination: true,
    supportsInstantRails: true,
    accountTypeHint: 'checking',
    executionReadiness: 'staged',
    supportedRails: ['ACH', 'wire', 'RTP', 'FedNow (bank dependent)'],
    description:
      'Treasury operations control layer for payments, approval workflows, reconciliation, and execution status across multiple bank rails.',
  },
  {
    providerKey: 'unit',
    label: 'Unit Embedded Banking',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: true,
    supportsWireOrigination: true,
    supportsInstantRails: false,
    accountTypeHint: 'checking',
    executionReadiness: 'staged',
    supportedRails: ['embedded bank accounts', 'ACH', 'wire', 'cards', 'statements'],
    description:
      'Embedded banking provider profile for business deposit accounts, account-backed ERP cashflow, card programs, statements, and bank-partner controlled movement.',
  },
  {
    providerKey: 'mercury',
    label: 'Mercury Business Banking',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: true,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'checking',
    executionReadiness: 'staged',
    supportedRails: [
      'business account sync',
      'balances',
      'transactions',
      'statements',
      'cards',
      'recipients',
      'payment to existing recipient (Mercury approval / token scoped)',
      'ClearFlow referral signup path pending referral URL',
    ],
    description:
      'Business banking integration profile for Mercury accounts. Use API-token or approved OAuth posture for account, balance, transaction, statement, card, treasury, and recipient sync; payment execution remains Mercury approval and credential scoped. Add ClearFlow’s Mercury referral URL before routing new-account signup traffic.',
    referralSignupUrl: 'https://mercury.com/r/clearflow',
  },
  {
    providerKey: 'checkbook',
    label: 'Checkbook',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: true,
    supportsWireOrigination: false,
    supportsInstantRails: true,
    accountTypeHint: 'checking',
    executionReadiness: 'staged',
    supportedRails: ['digital check', 'mailed check', 'ACH', 'RTP', 'virtual card'],
    description:
      'Bill-pay bridge for printable, mailed, and digital check execution, plus ACH and instant-payment posture when provider credentials are enabled.',
  },
  {
    providerKey: 'closinglock',
    label: 'Closinglock',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: false,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['wire instruction verification', 'payoff verification', 'payment request portal', 'title / escrow confirmation capture'],
    description:
      'Real-estate closing security profile for title and escrow workflows. Use to verify wire/payoff instructions and retain payment-request evidence; the actual cash-to-close wire still releases through the user bank or treasury provider.',
  },
  {
    providerKey: 'closesimple',
    label: 'CloseSimple',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: false,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['title company portal', 'buyer / seller communication', 'wire instruction delivery', 'closing milestone status'],
    description:
      'Title-company communication profile for closing updates, wire-instruction delivery posture, and milestone evidence. Treat as communications/proof unless a specific title-company integration confirms payment execution support.',
  },
  {
    providerKey: 'payload_keybox',
    label: 'Payload Keybox',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: true,
    supportsWireOrigination: true,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['real estate payment portal', 'ACH', 'wire', 'earnest money', 'cash to close', 'settlement reporting'],
    description:
      'Real-estate payment platform profile for title, escrow, and closing payments where Payload/Keybox is enabled by the closing office. Use for payment request, execution status, settlement reporting, and reconciliation when contracted credentials exist.',
  },
  {
    providerKey: 'earnnest',
    label: 'Earnnest',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: true,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'checking',
    executionReadiness: 'staged',
    supportedRails: ['earnest money deposit', 'ACH transfer', 'escrow deposit confirmation', 'receipt capture'],
    description:
      'Earnest-money deposit profile for real-estate contracts using Earnnest. Use for EMD collection, escrow confirmation, receipt capture, and acquisition ledger linkage; cash-to-close wire remains a separate title/bank rail.',
  },
  {
    providerKey: 'titleeq',
    label: 'TitleEQ',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: false,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['title order workflow', 'settlement workflow', 'closing status', 'document and fee evidence'],
    description:
      'Title-production and settlement workflow profile for title agencies using TitleEQ. Use for closing status, documents, fee evidence, and title workflow linkage; direct payment execution depends on the agency stack.',
  },
  {
    providerKey: 'escrow_com',
    label: 'Escrow.com',
    category: 'treasury',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: true,
    supportsWireOrigination: true,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['online escrow', 'wire payment', 'ACH', 'card', 'milestone release', 'escrow status'],
    description:
      'Online escrow profile for transactions where Escrow.com is an accepted escrow intermediary. Use for escrow instructions, buyer funding, milestone acceptance, release status, and retained escrow proof.',
  },
  {
    providerKey: 'tyler_payments',
    label: 'Tyler Payments / TPE',
    category: 'government',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['government checkout', 'card', 'e-check / ACH debit', 'reporting', 'agency receipt capture'],
    description:
      'Government payment processor profile for courts, state agencies, and local agencies using Tyler / NIC-style payment rails. Treat as vendor-credential and agency-contract scoped before enabling live checkout or transaction posting.',
  },
  {
    providerKey: 'tyler_odyssey_file_serve',
    label: 'Tyler Odyssey File & Serve',
    category: 'government',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['court e-filing fees', 'case / docket reference', 'filing receipt', 'payment confirmation', 'court CMS status'],
    description:
      'Court e-filing and payment profile for jurisdictions using Tyler Odyssey File & Serve. Use for docket-linked filing fees, case references, confirmation receipts, and court status capture rather than treating docket value as spendable settlement.',
  },
  {
    providerKey: 'payit',
    label: 'PayIt Government Payments',
    category: 'government',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['state agency portal', 'digital government checkout', 'cards', 'bank payment', 'receipt capture'],
    description:
      'Digital government payment profile for state and local agency portals. Use for searchable agency payees, payment-link handoff, retained confirmation numbers, and reconciliation once PayIt or agency integration credentials exist.',
  },
  {
    providerKey: 'catalis_court_payments',
    label: 'Catalis / nCourt Court Payments',
    category: 'government',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['court fines', 'fees', 'citations', 'card payments', 'e-check', 'court receipt capture'],
    description:
      'Court-focused payment provider profile for fines, fees, citations, and other justice payments. Use as a court payee rail with jurisdiction, case number, docket, receipt, and confirmation validation before marking paid.',
  },
  {
    providerKey: 'journal_epay_it',
    label: 'Journal Technologies ePay-it',
    category: 'government',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['court payments', 'e-filing fees', 'case number capture', 'receipt import', 'court portal handoff'],
    description:
      'Court payment and e-filing payment profile for courts using Journal Technologies products. Keep payment execution tied to the court portal/provider receipt and docket reference before clearing the obligation.',
  },
  {
    providerKey: 'imagesoft_truefiling',
    label: 'ImageSoft TrueFiling',
    category: 'government',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['court e-filing', 'filing fee checkout', 'case / docket reference', 'accepted filing receipt', 'payment evidence'],
    description:
      'Court e-filing payment profile for TrueFiling jurisdictions. Use for filing-fee checkout, accepted filing proof, receipt capture, and ledger reconciliation scoped to the court case.',
  },
  {
    providerKey: 'lexisnexis_government_payments',
    label: 'LexisNexis Government Payments',
    category: 'government',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['government portal handoff', 'agency payment confirmation', 'case or filing reference capture'],
    description:
      'Government payment and filing-adjacent provider profile for agency or court workflows where LexisNexis-operated services are in use. Keep execution staged until a specific agency endpoint and contract path are confirmed.',
  },
  {
    providerKey: 'gov_pay',
    label: 'Gov-Pay Court / Agency Portal',
    category: 'government',
    connectionRail: 'manual_profile',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: false,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'institution_dependent',
    supportedRails: ['online payment page', 'credit card', 'debit card', 'electronic check', 'settlement email capture'],
    description:
      'Portal-style government and municipal court payment profile. Use for agency search, payment-link handoff, confirmation upload, settlement email capture, and ledger reconciliation when no direct API exists.',
  },
  {
    providerKey: 'usps_bcg',
    label: 'USPS Business Gateway',
    category: 'postal',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: false,
    supportsSettlementInitiation: false,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['mailing services', 'Intelligent Mail', 'Informed Visibility', 'proof of mailing'],
    description:
      'Postal execution profile for business mailings, tracking, and retained delivery evidence when enforcement, notices, or remittance packets must move through USPS business mail services.',
  },
  {
    providerKey: 'upu_addressing',
    label: 'UPU Addressing Standards',
    category: 'postal',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: false,
    supportsSettlementInitiation: false,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['international address normalization', 'S42 templates', 'postal identifiers'],
    description:
      'International postal addressing posture for normalizing destination addresses and improving trusted delivery on cross-border mail and parcel dispatches.',
  },
  {
    providerKey: 'stripe',
    label: 'Stripe',
    category: 'processor',
    connectionRail: 'oauth',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: false,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['membership billing', 'ACH debit', 'processor payouts', 'card settlement', 'Treasury / Issuing when eligible'],
    description:
      'Membership billing, card and ACH acceptance, processor settlement, and staged Treasury or Issuing expansion for eligible platform accounts.',
  },
  {
    providerKey: 'cash_app',
    label: 'Cash App Pay via Square',
    category: 'processor',
    connectionRail: 'oauth',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: false,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: true,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['Cash App Pay checkout acceptance', 'Square Payments settlement'],
    description:
      'Save Cash App Pay acceptance posture through Square. This is not treated as arbitrary peer-to-peer Cash App sending.',
  },
  {
    providerKey: 'paypal',
    label: 'PayPal',
    category: 'processor',
    connectionRail: 'oauth',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: false,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['wallet payout', 'processor settlement'],
    description:
      'Retain a PayPal operating account profile for remittance, payout, and ledger routing while the direct provider connector stays staged.',
  },
  {
    providerKey: 'square',
    label: 'Square',
    category: 'processor',
    connectionRail: 'oauth',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: false,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'other',
    executionReadiness: 'staged',
    supportedRails: ['processor payout', 'merchant settlement'],
    description:
      'Keep a permanent Square-connected settlement profile inside the chart of accounts for processor-based cashflow and receipts.',
  },
  {
    providerKey: 'lithic',
    label: 'Lithic Card Issuing',
    category: 'card_program',
    connectionRail: 'api',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: true,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'credit_card',
    executionReadiness: 'staged',
    supportedRails: ['virtual cards', 'physical cards', 'spend controls', 'card transaction webhooks'],
    description:
      'Card issuing profile for controlled business cards, spend rules, tokenized cards, transaction webhooks, and ERP expense posting.',
  },
  {
    providerKey: 'issuer_portal',
    label: 'Card / Credit Issuer',
    category: 'credit',
    connectionRail: 'manual_profile',
    availabilityStatus: 'profile_only',
    supportsLiveSync: false,
    supportsTransactionImport: false,
    supportsSettlementInitiation: false,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'credit_card',
    executionReadiness: 'staged',
    supportedRails: ['statement intake', 'manual remittance'],
    description:
      'Use for third-party credit cards, merchant cards, and revolving credit accounts when you want a permanent connected profile even before live issuer aggregation is turned on.',
  },
  {
    providerKey: 'manual',
    label: 'Manual Treasury Profile',
    category: 'treasury',
    connectionRail: 'manual_profile',
    availabilityStatus: 'bank_dependent',
    supportsLiveSync: false,
    supportsTransactionImport: true,
    supportsSettlementInitiation: false,
    supportsAchOrigination: false,
    supportsWireOrigination: false,
    supportsInstantRails: false,
    accountTypeHint: 'checking',
    executionReadiness: 'institution_dependent',
    supportedRails: ['manual ACH file', 'manual wire', 'bank bill pay', 'statement import'],
    description:
      'Use when execution happens through the bank or treasury desk directly and ClearFlow needs to retain the routing, proof, and reconciliation posture.',
  },
];

export function getFinancialConnectionProviders() {
  return providerCatalog;
}

export function getFinancialConnectionProvider(providerKey: FinancialConnectionProvider) {
  return providerCatalog.find((provider) => provider.providerKey === providerKey);
}
